- type: Workshop Organization
  description: Co-organizer of [E-pi UAI 2023](https://sites.google.com/view/epi-workshop-uai-2023/home?authuser=0)

- type: Conference Reviewer
  description: NeurIPS; ICLR; ICML; AAAI; IJCAI; AISTATS

- type: Journal Reviewer
  description: TMLR; IEEE SPL; IEEE OJCS

- type: Teaching
  description: Lab session of *AI in Embedded Systems* [B-KUL-B3076T]

- type: Master Thesis Supervision
  description: T. Demeulenaere and S. Francq (2022-2023); L. De Jonckheere (2022-2023); A. Beigrezaei (2023-2024)