- type: Workshop Organization
  description: Co-organizer of [E-pi UAI 2023](https://sites.google.com/view/epi-workshop-uai-2023/home?authuser=0)

- type: Conference Reviewer
  description: NeurIPS; ICLR; ICML; AAAI; IJCAI; UAI; AISTATS

- type: Journal Reviewer
  # description: IEEE TNNLS; TMLR; IEEE SPL; IEEE OJCS
  description: IEEE TNNLS; TMLR; IEEE OJCS

- type: Teaching Assistant
  description: AI in Embedded Systems [B-KUL-B3076T], KU Leuven, Spring 2023-2025

- type: Master Thesis Supervision
  description: T. Demeulenaere and S. Francq (2022-2023); L. De Jonckheere (2022-2023); A. Beigrezaei (2023-2024)